var test2 = {
  '單選題': [
    'B 1.(單選)以下為主控式創新(Dominant lnnovation)的創新關係圖(Relationship Mapping)，請問右下 角的圓圈是() A.成本 B.價值 C.品牌 D.速度 E.價格',
    'A 2.(單選)承上題，請問哪個是所謂的「蛋黃」() A.產品 B.使用者 C.成本 D.價值 E.品牌',
    'D 3.(單選)CPS 第一層為智能感應層(Connection)，其目的為() A.系統的動態優化與協同執行 B.對目標的識別與決策優化 C.隱性問題顯性化 D.統一有效的數據環境 E.鏡像建模與數據挖掘',
    'E 4.(單選)CPS 第三層為智能網絡層(Cyber)，其目的為() A.系統的動態優化與協同執行 B.對目標的識別與決策優化 C.隱性問題顯性化 D.統一有效的數據環境 E.鏡像建模與數據挖掘',
    'B 5.(單選)依照 IMS 提出的技術開發流程，包含1健康評估、2信號處理、3可用壽命預測、4 故障診斷、5特徵提取，請問正確的流程為() A.43125 B.25143 C.45213 D.23514 E.25413',
    'C 6.(單選)生産力管理模式五個層次中，我們現在正進行哪一層次() A.5S & Kaizen B.Lean & 6Sigma C.Predictive Tools D.Optimization E.Autonomous',
    'D 7.(單選)CPS 系統要建立的 M 是() A.Method B.Measurement C.Maintenance D.Models E.Machine',
    'D 8.(單選)CPS 最重要的目的為實現() A.製造 B.自造 C.智造 D.傳承 E.模型',
    'D 9.(單選)工業數據分析的核心是() A.大數據分析(Big Data) B.自動化機器人(Autonomous Robot) C.人工智慧(Artificial Intelligence) D.故障檢測與健康管理(Prognostics and Health Management) E.感測器(Sensor)',
    'C 10.(單選)工業大數據分析並不僅僅依靠演算法工具，而是更加注重() A.統計上的關聯性 B.邊緣計算能力 C.邏輯清晰的分析流程和與分析流程相匹配 D.雲端平臺計算能力 E.建立模型的共通性',
    'E 11.(單選)預測型製造的核心技術是() A.一個雲平臺 B.一個快捷的邊緣計算 C.一個快速 3D 打樣平臺 D.一個資料搜集平臺 E.一個包含智慧軟體進行預測建模的智慧計算工具',
    'A 12.(單選)工業 4.0 是以_____爲主導的第四次工業革命() A.智能製造 B.個性化定制 C.機器人自動化生産 D.3D 製造 E.工業雲',
    'C 13.(單選) 20 世紀 70 年代日本曾經提出以“全生産系統維護(TPM)”的提出零停機、零廢 品、零事故、_____的“4 零”目標() A.零庫存 B.零排放 C.零效率損失 D.零人工 E.零誤差',
    'B 14.(單選)煎蛋模型的目標是() A.核心産品 B.創值 C.客戶滿意度 D.產品功能 E.產品競爭力',
    'C 15.(單選)大數據分析可以分為 Descriptive、Prescriptive、______ 三種型式() A.Connection B.Analysis C.Predictive D.Comparison E.Control',
    'C 16.(單選)大數據分析主要有 Descriptive、Prescriptive、______ 三種型式() A.Connection B.Analysis C.Predictive D.Comparison E.Control',
    'A 17.(單選)______的核心就在於注重産品技術開發到注重顧客價值創造的思維轉變過程，實現從 創新到創值() A.主控式創新思維 B.持續性創新思維 C.破壞式創新思維 D.跨越性創新思維 E.架構性創新思維',
    'E 18.(單選)在數據分析過程中，從問題的產生到數據分析，要先做好數據的______() A.分類、分解、分析 B.分類、分割、分析 C.分辨、分割、分解 D.分辨、分類、分解 E.分類、分割、分解',
    'C 19.(單選)工業人工智能(Industrial AI)是一種實現人工智能在工程應用的系統訓練及方法，具 有快速性(speed)，系統性(systematic)外，還具有什麼特性() A.標準性(Standard) B.安全性(Security) C.可傳承性(Sustainable) D.服務性(Service) E.特殊性(Specifieness)',
    'B 20.(單選)工業大數據的意義包括數據的來源，________，數據的意義() A.數據的冗餘 B.數據的關係 C.數據的多樣 D.數據的時效 E.數據的維度',
    'E 21.(單選)大數據的 6 個 C 系統不包括() A.連接 B.雲端技術 C.虛擬網絡 D.社群 E.標準化的內容',
    'C 22.(單選)在帶鋸案例中，帶鋸使用的全生命信息分類錯誤的是() A.工況類:工件信息 B.特徵類:振動信號 C.工況類:質量參數 D.狀態類:健康狀態結果 E.狀態類:故障模式',
    'D 23.(單選)在帶鋸案例中，哪些不是全生命週期預測分析過程() A.從特徵提取聚類 B.每個聚類集群下的預測與決策 C.特徵與磨損階段的映射 D.對帶鋸特徵多加感應器 E.設備狀態特徵聚類分析',
  ],
  '多選題': [
    'ABD 24.(多選)Time-machine 是一種應用於對離散事件之間的關係性建構分析的方法，它的特性包括 哪些() A.離散性 B.方向性 C.普適性 D.時序性 E.安全性',
    'AD 25.(多選)智慧維護技術設計和開發流程七步驟包含需求定義、分析模型選擇、部署策略和實 驗設計、解決方案可行性分析和選擇、專案開發和實踐，請問缺少的兩步是() A.監控層次定義 B.團隊組織編制 C.績效考核制度 D.數據獲取計劃 E.績效獲取計劃',
    'BD 26.(多選)數據採集時可以考量的六種類數據，除了環境數據(溫、濕度等)、工況信息(生產 設定參數:進給、轉速等)、系統集成(MES、ERP 等)、工作狀態(傳感信號:震動、電流等) 以外，還有什麽() A.自動化規劃 B.績效數據 C.財務信息 D.維護維修記錄 E.監控規劃',
    'ABC 27.(多選)特徵提取方法大類分為哪幾類() A.時域 B.頻域 C.時頻域 D.間域 E.標域',
    'ABE 28.(多選)以下屬於數據合適性分析的有() A.分類分割 B.分解分析 C.分紅分利 D.分工分力 E.分享分憂',
    'ABCE 29.(多選)關鍵有效的大數據可以從以下哪些途徑得到() A.感應器，控制器 B.關係的量測 C.歷史記錄 D.圖紙標識 E.參數',
    'ABDE 30.(多選)工業人工智能的機會在於() A.需要解决的問題 B.需要預測的問題 C.單調及骯髒環境的問題 D.需要避免的問題 E.不可見的問題',
    'ABC 31.(多選)工業大數據技術核心是爲解决哪 3B 問題 () A.Broken B.Bad Quality C.Below Surface D.Bandwidth E.Bankruptcy',
    'BCE 32.(多選)李傑教授在《工業大數據》中提到的「蛋黃」/「蛋白」理論中「蛋黃」除了 Machine (機器)、Methods(工藝)、Measurement(測量)以外，還有哪些() A.Market(市場) B.Material(材料) C.Maintenance(維護) D.Manufacturing(製造) E.Modeling(建模)',
    'BCD 33.(多選)李傑教授在《工業大數據》中提到的「蛋黃」/「蛋白」理論中「蛋白」除 Connection (連接)、Cloud(雲)、Cyber(虛擬網絡)以外，還有哪些() A.Control(控制) B.Content/Context(數據內容與來源背景) C.Community (社群) D.Customization(定製化) E.Communication(溝通)',
    'ABDE 34.(多選)CPS 技術的應用，設備需具備哪些能力() A.自我預測(Self-Predict) B.自我比較(Self-Compare) C.自我分析(Self-Analysis) D.自動察覺(Self-Aware) E.自我配置(Self-Configure)',
    'ACD 35.(多選)大數據具有 4V 的特徵，除了包括量(Volume)外，還具備哪些() A.速度(Velocity) B.有效的(Valid) C.多樣性(Variety) D.真實性(Veracity) E.大量的(Vast)',
    'ACDE 36.(多選)工業數據除具有更強的專業性外，還有哪些特點() A.關聯性 B.目的性 C.時序性 D.解析性 E.流程性',
    'BCDE 37.(多選)對於工業 4.0 的智慧製造轉型而言，工業大數據的核心價值目標是什麽() A.將産品功能與用戶需求相結合 B.將客製化與規模化結合 C.個性化與大眾化結合 D.微觀與宏觀結合 E.現在與未來結合',
    'ABCDE 38.(多選)工業 4.0 環境下的 CPS 技術體系架構，包括了哪幾個層次的建構模式() A.智能感知層 B.資訊挖掘層 C.網路層 D.認知層 E.配置層',
    'BCD 39.(多選)網絡層的主要功能包括以下哪幾種() A.連接(Connection) B.通信(Communication) C.計算(Computation) D.比較(Comparison) E.控制(Control)',
    'ABCDE 40.(多選)生産力管理模式中，包括以下哪幾種模式() A.發送模式 B.精密與 6 Sigma 模式 C.預測分析模式 D.決策管理優化模式 E.啓動協會優化模式',
    'ABCDE 41.(多選)使用工業人工智能工具(Industrial AI Tools)在每一個場域，主要包括以下哪幾種() A.速度(Speed) B.及時性(Timeliness) C.精度(Precisian) D.複雜性(Complexity) E.不確定性(Uncertaincy)',
    'BCD 42.(多選)CPS 以多種數據的建模爲基礎，以智能連接(Connection)，智能分析(Conversion)， 及_______的 5C 體系等主要架構() A.智能檢測(Check) B.智能網路(Cyber) C.智能認知(Cognition) D.智能配置執行(Configuration) E.智能傳送(Carry)',
    'BDE 43.(多選)集團強調工業互聯網爲目前發展最重要的核心，其中六流包含三虛、三實，三虛包 含下列哪三流() A.人流 B.訊流 C.物流 D.金流 E.技術流',
    'ACE 44.(多選)集團強調工業互聯網爲目前發展最重要的核心，其中六流包含三虛、三實，三實包 含下列哪三流() A.人流 B.金流 C.物流 D.訊流 E.過程流',
    'ABE 45.(多選)以下哪些是預後推估的流程階段() A.Clustering B.Selection of Baseline and Critical Units C.End-to-End modeling D.Classification E.Peer-to-Peer Comparison',
    'BE 46.(多選)以下哪些不在局部缺陷評估的典型流程中() A.Signal Processing and Feature Extraction B.Data Augmentation C.Fault Localization D.Fault Type Identification E.Resource Assessment',
    'BCD 47.(多選)在 Nissan 機器人健康聯網系統裡，包含了哪些必要組件() A.搜尋引擎 B.服務器 C.整合製造系統 D.數據庫 E.JTAG',
  ],
  '判斷題': [
    'O 48.(判斷)依據數據是否有標籤可將建模分析方法分為監督式學習與非監督式學習()',
    'X 49.(判斷)有個榔頭什麽都能敲，有了 AI 什麽都能解决()',
    'O 50.(判斷)使用 CPS 及高端數據處理是因爲數據量大及多類()',
    'X 51.(判斷)推動中國製造的技術創新、模式創新和服務創新，中國企業面臨的最大挑戰是將增 長重點從「蛋白」向內轉到「蛋黃」上()',
    'O 52.(判斷)智能製造系統運行的邏輯是:發生問題→分析問題(模型)→模型調整 5 個要素→ 解決問題→模型積累經驗，並分析問題的根源→模型調整 5 個要素→避免問題()',
    'O 53.(判斷)一個製造系統是否能夠被稱爲智能，主要判斷其是否具備以下兩個特徵:(1)是否 能夠學習人的經驗，從而替代人來分析問題和形成決策;(2)能否從新的問題中積累經驗，從而 避免問題的再次發生()',
    'O 54.(判斷)有別于互聯網大數據，工業大數據的分析技術核心要解决的問題是 Below Surface、 Broken、Bad Quality ()',
    'X 55.(判斷)大數據與智能製造三個重要元素之間的關係是數據->問題->知識(模型)()',
    'O 56.(判斷)創值就是客戶欣賞你的産品，願意花時間購買，這樣你的未來才是美好的()',
    'O 57.(判斷)在工業 4.0 中，大數據邏輯應該有兩個 V，一是可見性(Visibility)，即透過大數據分 析使以往未見的重要因素和資訊變得可見，二是價值(Value)，即透過大數據分析所得到的資訊 應該被轉換成價值()',
    'X 58.(判斷)對於零組件或是設備的健康衰退評估可以用 CV 值(Confidence Value)來表達:CV 是一個 0~1 之間的無因次量，1 代表衰退到不可接受的狀態，0 代表健康狀態(又稱健康基線狀 態)()',
    'X 59.(判斷)在[煎蛋模型]理論，「蛋白」是核心産品，而「蛋黃」則是真正為客戶創造價值的創 新服務，是能讓企業持續性獲利的關鍵()',
    'O 60.(判斷)在工業大數據中提到，企業的創新模式包括，持續性創新(Continuous Innovation)， 跨越性創新(Discontinuous Innovation)及主控式創新三種()',
    'O 61.(判斷)主控式創新工具，可以包括:創新矩陣(Innovation Matrix)、生產者、產品與服務關 係三角圈(Relationship Map)、應用地圖(Application Space Mapping)()',
    'O 62.(判斷)連網數據收集要做到全方位設備數據，主要包括:環境參數、系統整合、績效數據、 維護保養記錄、工作狀態數據、狀態資訊六個項目()',
    'X 63.(判斷)固定週期下的固定特徵分析(FCFT)及自使用性資料獲取而設計，僅限用於具備常 規固定運行模式及事件激勵的運行模式()',
    'O 64.(判斷)特徵(Features)是從原始數據中提取的精煉信息(Compact information extracted from raw data)()',
    'O 65.(判斷)維護技術的發展包括:Reactive Maintenance、 Preventive Maintenance、Condition-Based Maintenance、 Prognostics and Health Management()',
    'O 66.(判斷)集團互聯網就是雲移物大智網+機器人()',
    'O 67.(判斷)新工業革命環境下的中國製造模式轉型方式是推動“智慧的參與者”、“智慧的製 造”和“智慧的産品”三者的協調互聯 ()',
    'O 68.(判斷)CPS 以 5C 體系爲架構，5C 可以指智能連接 Connection、智能分析 Conversion、智能 網路 Cyber、智能認知 Cognition 和智能配置與執行 Configuration()',
    'X 69.(判斷)CPS 的廣義內涵，是實體系統(Physical System)中的比較性(Comparison)、關係性 (Correlation)和一致性(Consistency)的對稱性分析、預測、優化和管理()',
  ],
};